# ===== Perfil H2 en Memoria =====
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.flyway.enabled=false

restaurant.name=MesaQR Local H2
restaurant.iva.habilitado=true
spring.jpa.defer-datasource-initialization=true
restaurant.iva.porcentaje=16
restaurant.propina.habilitada=true
restaurant.propina.porcentaje=10
restaurant.qr.tamanio=300
restaurant.token.duracion-horas=24
restaurant.retry.max-intentos=3
restaurant.retry.delay-ms=10
restaurant.webhook.secret=secret_h2
restaurant.cors.allowed-origins=*

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.com.restaurant=DEBUG
